config/routes.rb
Rails.application.routes.draw do
  resources :books, except: [:show]
  resources :authors, except: [:show]
  resources :publishers, except: [:show]

  root to: 'dashboard#index'
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_and_belongs_to_many :books

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/author_book.rb
class AuthorBook < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_and_belongs_to_many :authors
  belongs_to :publisher

  validates :isbn, uniqueness: true, format: { with: /\A\d+\Z/, message: 'must be digits only' }
  validates :title, presence: true

  before_validation :sanitize_isbn

  private

  def sanitize_isbn
    self.isbn = isbn.gsub(/-/, '')
  end
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :find_author, only: [:edit, :update, :destroy]

  def index
    @authors = Author.order(last_name: :asc, first_name: :asc)
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to authors_path, success: 'The author has been created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @author.update(author_params)
      redirect_to authors_path, success: 'The author has been updated.'
    else
      render :edit
    end
  end

  def destroy
    @author.destroy
    redirect_to authors_path, success: 'The author has been deleted.'
  end

  private

  def find_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:edit, :update, :destroy]

  def index
    @books = Book.all.order(title: :asc)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path, success: 'The book has been created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to books_path, success: 'The book has been updated.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, success: 'The book has been deleted.'
  end

  private

  def find_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:isbn, :title, :subtitle, :publisher_id, :release_date, :price, :edition, :pages, :abstract)
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :find_publisher, only: [:edit, :update, :destroy]

  def index
    @publishers = Publisher.order(name: :asc)
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)

    if @publisher.save
      redirect_to publishers_path, success: 'The publisher has been created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @publisher.update(publisher_params)
      redirect_to publishers_path, success: 'The publisher has been updated.'
    else
      render :edit
    end
  end

  def destroy
    @publisher.destroy
    redirect_to publishers_path, success: 'The publisher has been deleted.'
  end

  private

  def find_publisher
    @publisher = Publisher.find(params[:id])
  end

  def publisher_params
    params.require(:publisher).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(type)
    case type.to_sym
    when :success then "alert-success"
    when :alert then "alert-danger"
    when :notice then "alert-info"
    else type.to_s
    end
  end
end

app/views/authors/edit.html.haml
%h1
  = "Edit \"#{@author.first_name} #{@author.last_name}\""
  .pull-right= link_to 'Delete Author', @author, method: :delete, class: 'btn btn-danger'

= form_for @author, html: { class: 'form-horizontal' } do |f|
  .form-group
    = f.label :first_name, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :first_name, class: 'form-control'

  .form-group
    = f.label :last_name, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :last_name, class: 'form-control'

  .form-group
    .col-sm-10.col-sm-push-2
      = f.submit 'Update Author', class: 'btn btn-lg btn-success'
      = link_to 'Cancel', authors_path, class: 'btn'

app/views/authors/index.html.haml
%h1
  .pull-right= link_to 'Create Author', new_author_path, class: 'btn btn-success'
  All Authors Huy

- if @authors.count > 0
  .item-list.row
    - @authors.in_groups(4, false) do |authors|
      .col-sm-3.list-column
        %ul
          - authors.each do |author|
            %li.list-item= link_to "#{author.last_name}, #{author.first_name}", edit_author_path(author)
- else
  %em There are no authors yet.

app/views/authors/new.html.haml
%h1 Create New Author

= form_for @author, html: { class: 'form-horizontal' } do |f|
  .form-group
    = f.label :first_name, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :first_name, class: 'form-control'

  .form-group
    = f.label :last_name, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :last_name, class: 'form-control'

  .form-group
    .col-sm-10.col-sm-push-2
      = f.submit 'Create Author', class: 'btn btn-lg btn-success'
      = link_to 'Cancel', authors_path, class: 'btn'

app/views/books/edit.html.haml
%h1 Edit Book

= form_for @book, html: { class: 'form-horizontal' } do |f|
  - if @book.errors.any?
    .alert.alert-danger
      %button.close{ data: { dismiss: 'alert' } } ×
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :isbn, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :isbn, class: 'form-control'

  .form-group
    = f.label :title, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :subtitle, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :subtitle, class: 'form-control'

  .form-group
    = f.label :publisher_id, 'Publisher', class: 'control-label col-sm-2'
    .col-sm-10
      = f.collection_select :publisher_id, Publisher.order(:name), :id, :name, {}, class: 'form-control select2-input'

  .form-group
    = f.label :release_date, class: 'control-label col-sm-2'
    .col-sm-10
      = f.date_field :release_date, class: 'form-control'

  .form-group
    = f.label :price, class: 'control-label col-sm-2'
    .col-sm-10
      .input-group
        %span.input-group-addon $
        = f.number_field :price, class: 'form-control money-control', step: :any

  .form-group
    = f.label :edition, class: 'control-label col-sm-2'
    .col-sm-10
      = f.number_field :edition, class: 'form-control', min: 1

  .form-group
    = f.label :pages, class: 'control-label col-sm-2'
    .col-sm-10
      = f.number_field :pages, class: 'form-control', min: 1

  .form-group
    = f.label :abstract, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_area :abstract, class: 'form-control', rows: 5

  .form-group
    .col-sm-10.col-sm-push-2
      = f.submit 'Update Book', class: 'btn btn-lg btn-success'
      = link_to 'Return to list', books_path, class: 'btn'

app/views/books/index.html.haml
%h1
  Books
  .pull-right= link_to 'Create Book', new_book_path, class: 'btn btn-success'

%p Use this area to manage the books you have in stock. This can also be extended to import books autmatially from a source.

%table.table.table-striped
  %thead
    %tr
      %th ISBN
      %th Title
      %th Publisher
      %th Price
      %th
  %tbody
    - if @books.count > 0
      - @books.each do |book|
        %tr
          %td= book.isbn
          %td= book.title
          %td= book.publisher.name if book.publisher
          %td= number_to_currency book.price
          %td.text-right
            = link_to 'Edit', edit_book_path(book), class: 'btn btn-xs btn-warning'
            = link_to 'Delete', book_path(book), method: :delete, class: 'btn btn-xs btn-danger'
    - else
      %tr
        %td(colspan=5)
          %em
            You have no books in your inventory right now.
            = link_to 'Add one.', new_book_path

app/views/books/new.html.haml
%h1 New Book

= form_for @book, html: { class: 'form-horizontal' } do |f|
  - if @book.errors.any?
    .alert.alert-danger
      %button.close{ data: { dismiss: 'alert' } } ×
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :isbn, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :isbn, class: 'form-control'

  .form-group
    = f.label :title, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :subtitle, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :subtitle, class: 'form-control'

  .form-group
    = f.label :publisher_id, 'Publisher', class: 'control-label col-sm-2'
    .col-sm-10
      = f.collection_select :publisher_id, Publisher.order(:name), :id, :name, {}, class: 'form-control select2-input'

  .form-group
    = f.label :release_date, class: 'control-label col-sm-2'
    .col-sm-10
      = f.date_field :release_date, class: 'form-control'

  .form-group
    = f.label :price, class: 'control-label col-sm-2'
    .col-sm-10
      .input-group
        %span.input-group-addon $
        = f.number_field :price, class: 'form-control money-control', step: :any

  .form-group
    = f.label :edition, class: 'control-label col-sm-2'
    .col-sm-10
      = f.number_field :edition, class: 'form-control', min: 1

  .form-group
    = f.label :pages, class: 'control-label col-sm-2'
    .col-sm-10
      = f.number_field :pages, class: 'form-control', min: 1

  .form-group
    = f.label :abstract, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_area :abstract, class: 'form-control', rows: 5

  .form-group
    .col-sm-10.col-sm-push-2
      = f.submit 'Create Book', class: 'btn btn-lg btn-success'
      = link_to 'Return to list', books_path, class: 'btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title OrderBook
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{ type: 'button', data: { toggle: false, target: '#navbar-toggle-container' }, aria: { expanded: false } }
            %span.sr-only Toggle Navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'OrderBook', root_path, class: 'navbar-brand'

        #navbar-toggle-container.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to 'Books', books_path
            %li= link_to 'Authors', authors_path
            %li= link_to 'Publishers', publishers_path

    .container
      - flash.each do |type, message|
        %div{ class: "alert fade in #{bootstrap_class_for(type)}" }
          %button.close{ data: { dismiss: 'alert' } } ×
          = message

      = yield

app/views/publishers/edit.html.haml
%h1
  = "Edit \"#{@publisher.name}\""
  .pull-right= link_to 'Delete Publisher', @publisher, method: :delete, class: 'btn btn-danger'

= form_for @publisher, html: { class: 'form-horizontal' } do |f|
  .form-group
    = f.label :name, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :name, class: 'form-control'

  .form-group
    .col-sm-10.col-sm-push-2
      = f.submit 'Update Publisher', class: 'btn btn-lg btn-success'
      = link_to 'Cancel', publishers_path, class: 'btn'

app/views/publishers/index.html.haml
%h1
  .pull-right= link_to 'Create Publisher', new_publisher_path, class: 'btn btn-success'
  Publishers

- if @publishers.count > 0
  .item-list.row
    - @publishers.in_groups(4, false) do |publishers|
      .col-sm-3.list-column
        %ul
          - publishers.each do |publisher|
            %li.list-item= link_to publisher.name, edit_publisher_path(publisher)
- else
  %em There are no publishers yet.

app/views/publishers/new.html.haml
%h1 Create New Publisher

= form_for @publisher, html: { class: 'form-horizontal' } do |f|
  .form-group
    = f.label :name, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :name, class: 'form-control'

  .form-group
    .col-sm-10.col-sm-push-2
      = f.submit 'Create Publisher', class: 'btn btn-lg btn-success'
      = link_to 'Cancel', publishers_path, class: 'btn'